channels:
- defaults
dependencies:
- python=3.10
- pip:
  - numpy==1.26.2
  - pandas==2.1.4
  - spacy==3.0.9
  - scikit-learn==1.3.2
  - alt-profanity-check==1.3.2
  - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
name: chatbot
